# Form implementation generated from reading ui file 'c:\Users\j9211\Desktop\backup\Excel2Word\Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_Name = QtWidgets.QLabel(self.centralwidget)
        self.Label_Name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Label_Name.setObjectName("Label_Name")
        self.gridLayout.addWidget(self.Label_Name, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEdit_name.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 3, 0, 1, 1)
        self.Button_Excel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Excel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Button_Excel.setObjectName("Button_Excel")
        self.gridLayout.addWidget(self.Button_Excel, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(150, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(100, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 1, 1)
        self.Label_Excel = QtWidgets.QLabel(self.centralwidget)
        self.Label_Excel.setMinimumSize(QtCore.QSize(200, 0))
        self.Label_Excel.setText("")
        self.Label_Excel.setObjectName("Label_Excel")
        self.gridLayout.addWidget(self.Label_Excel, 0, 1, 1, 2)
        self.Button_GO = QtWidgets.QPushButton(self.centralwidget)
        self.Button_GO.setObjectName("Button_GO")
        self.gridLayout.addWidget(self.Button_GO, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_Name.setText(_translate("MainWindow", "Output name"))
        self.Button_Excel.setText(_translate("MainWindow", "EXCEL"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Idle ....</p></body></html>"))
        self.Button_GO.setText(_translate("MainWindow", "Go"))
